name: lung-cancer-detection
channels:
  - conda-forge
  - defaults
  - simpleitk
dependencies:
  - python=3.7
  - numpy=1.18.1
  - imageio=2.6.1
  - ipykernel
  - matplotlib=3.1.3
  - numexpr=2.7.1
  - pandas=1.0.1
  - path=13.1.0
  - path.py=12.4.0
  - pip=20.0.2
  - pkginfo
  - scikit-learn=0.22.1
  - scikit-image=0.16.2
  - scipy=1.4.1
  - statsmodels=0.11.0
  - simpleitk=1.2.4
