name: lung-cancer-detection
channels:
  - conda-forge
  - defaults
  - simpleitk
dependencies:
  - black
  - imageio=2.6.1
  - ipykernel
  - jupyter=1.0.0
  - matplotlib=3.2.1
  - numpy=1.18.1
  - opencv=3.4.2
  - pandas=1.0.1
  - pathlib=1.0.1
  - pip=20.0.2
  - pydicom=1.4.2
  - python=3.7
  - scikit-image=0.16.2
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - simpleitk=1.2.4
  - statsmodels=0.11.0
  - tqdm=4.15.0
  - keras=2.3.1
  - openblas=0.2.19
  - pydot=1.4.1
  - pip:
      - tensorflow==2.2
      - plot-keras-history==1.1.23
      - tensorboard=2.2
